# Generated by Django 3.2.22 on 2023-11-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20231122_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date',
        ),
    ]
