# Generated by Django 3.2.22 on 2023-11-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_service_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='booked',
        ),
        migrations.AddField(
            model_name='product',
            name='is_special_offer',
            field=models.BooleanField(default=False, verbose_name='Special Offer'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_special_offer',
            field=models.BooleanField(default=False, verbose_name='Special Offer'),
        ),
    ]
