# Generated by Django 3.2.22 on 2023-11-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20231122_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='base_price',
            new_name='price',
        ),
    ]
