# Generated by Django 3.2.22 on 2023-11-26 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20231126_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonschedule',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_schedules', to='product.service'),
        ),
    ]
