# Generated by Django 3.2.22 on 2023-11-26 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_lessonschedule_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonschedule',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_schedules', to='product.service'),
        ),
    ]
