# Generated by Django 3.2.22 on 2023-11-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20231120_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='base_price',
        ),
    ]
