# Generated by Django 3.2.22 on 2023-11-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20231122_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lessonschedule',
            name='time_slot',
            field=models.CharField(choices=[('09:30', '9:30 AM'), ('11:00', '11:00 AM'), ('13:00', '1:00 PM'), ('14:30', '2:30 PM'), ('16:00', '4:00 PM')], max_length=5),
        ),
    ]
