# Generated by Django 3.2.22 on 2023-12-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='max_participants',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
